---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
      - id: detect-private-key
        name: Detect private key
      - id: end-of-file-fixer
        name: Fix end of files
      - id: fix-byte-order-marker
        name: Fix utf-8 byte order marker
      - id: trailing-whitespace
        name: Trim trailing whitespace
