= Python Project Template

Use this template to bootstrap new Python projects fast and unified.

To create a new project, install and run https://github.com/cookiecutter/cookiecutter[Cookiecutter]

[source,console]
----
$ cookiecutter https://github.com/andreaslongo/cc-python.git
----

Or install and use https://github.com/pipxproject/pipx[pipx] (recommended)

[source,console]
----
$ pipx run cookiecutter https://github.com/andreaslongo/cc-python.git
----


== Features

- https://www.gnu.org/software/make/[GNU Make] for workflow automation
- https://github.com/pre-commit/pre-commit[pre-commit] for Git hooks
- https://github.com/pyenv/pyenv[pyenv] for Python version management
- https://github.com/jazzband/pip-tools[pip-tools] for Python dependency management
- https://pytest.org/[pytest] for unit tests
- http://mypy-lang.org/[mypy] for static type checks
- https://flake8.pycqa.org[flake8] for static code analysis


== Python Dependency Management

[source,console]
----
python-project/
| requirements-dev.in
| requirements-dev.txt
| requirements.in
| requirements.txt
----

- `.in` files are dependencies
- `.txt` files are pinned and hashed results of `pip-compile`

=== Environments

Depending on the environment, the dependencies of Python packages may vary.

Run `pip-compile` on each environment to generate different `.txt` files, valid for each environment.
You can use the same `.in` file for all environments.

- Environment (simplified) = Operating System + Python version (3.8, 3.9, ...) + Python interpreter (CPython, PyPy, ...)
- https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile[Cross-environment usage of `requirements.in`/`requirements.txt` and `pip-compile`]
