[nitpick]

[nitpick.files.present]


["setup.cfg"."tool:pytest"]
addopts = "--strict-config --strict-markers --doctest-modules --cov --cov-report=term-missing"
#--tb=short

["setup.cfg"."coverage:run"]
branch = true
source = "."
omit = "setup.py"


["setup.cfg".mypy]
strict = true
pretty = true
#show_column_numbers = true
#show_error_codes = true
#show_error_context = true

["setup.cfg".mypy-setuptools]
ignore_missing_imports = true


["setup.cfg".flake8]
show-source = true
doctests = true
max-line-length = 88
max-complexity = 6
#statistics = false

select = "B, B9, C, E, F, S, W"
# B: Bugbear
# B9: Bugbear opinions
# C: Complexity (McCabe)
# E: Errors (pycodestyle)
# F: Fatals (PyFlakes)
# S: Security (Bandit)
# W: Warnings (pycodestyle)

per-file-ignores = "test/*:S101"
# ignore = B950, E203, W503
# B008: Do not perform function calls in argument defaults.
# B950: Line too long (line is > max-line-length + 10%)
# E203: Whitespace before ':', not PEP 8 compliant
# E266: Too many leading '#' for block comment
# E402: Import at top, too many circular import fixes
# E501: Line too long (82 > 79 characters), handled by Bugbear B950
# E722: Bare except, handled by Bugbear B001
# F811: Redefinition of unused function/method
# S101: Use of assert detected.
# W503: Line break before binary operator, not PEP 8 compliant
